# ansible/inventory.ini
# Dostosuj IP do swoich VM w VirtualBox

[devops]
vm1 ansible_host=192.168.56.10 ansible_user=devops

[build]
vm2 ansible_host=192.168.56.20 ansible_user=devops

[production]
vm3 ansible_host=192.168.56.30 ansible_user=devops

[all:vars]
ansible_ssh_private_key_file=/var/lib/jenkins/.ssh/melanoma_ci_rsa
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
